# Generated by Django 3.2.8 on 2021-10-24 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20211022_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auter',
            new_name='author',
        ),
    ]
